/** @format */

import Link from 'next/link';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<link
				rel="stylesheet"
				href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css"
			></link>
			<body>
				<nav>
					<ul>
						<li>
							<strong>Pantry Planner</strong>
						</li>
					</ul>
					<ul>
						<li>
							<Link href="/login">Login</Link>
						</li>
						<li>
							<Link href="/signup">Signup</Link>
						</li>
						<li>
							<a href="#" role="button">
								Button
							</a>
						</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
